name: Build My Application

on: [push]

jobs:
  build: 
    name: Build Our App
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v4
      - name: Print Current Directory
        run: pwd
      - name: List Files and Directories in Root
        run: ls
      - name: Check for .NET CLI
        run: dotnet build
      - name: List All Files
        run: ls TrickingLibraryApi/ -R
      - name: Check for NPM Version
        run: npm -v
