name: Build My Application

on: [push]

jobs:
  build: 
    name: Build Our App
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4
      - name: Print current directory
        run: pwd
      - name: Build with .NET CLI
        run: dotnet build
      - name: List all files
        run: ls TrickingLibraryApi/ -R
      - name: Check NPM version
        run: npm -v
